---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echoapp-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: echoapp-dev
  chart:
    git: git@github.com:edenavital5/echo_app_helm_chart.git
    path: charts/echo
    ref: dev
  values:
    image:
      repository: edenavital/echo-app
      tag: dev-28b610bc8d25ca4237d483a1b4a02bacb56ce12d      
    replicaCount: 1
    hpa:
      enabled: false
