---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echoapp-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.4
spec:
  releaseName: echoapp-prod
  chart:
    git: git@github.com:edenavital5/echo_app_helm_chart.git
    path: charts/echo
    ref: master
  values:
    image:
      repository: natalicot/echo-app
      tag: 0.4.11
    replicaCount: 3
