apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
     kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Values.ingress.hosts.host }}
    http:
      paths:
      - backend:
          serviceName: echo-app
          servicePort: 80
