apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-map
  namespace: dev
  labels:
    {{- include "echo.labels" . | nindent 4 }}

env:
- name: MY_NAMESPACE
  valueFrom:
    fieldRef:
        fieldPath: metadata.namespace

data:
  PORT: '3000'
  LOGLEVEL: 'debug'