apiVersion: v1
kind: Service
metadata:
  name: echo-app
  labels:
    {{- include "echo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "echo.selectorLabels" . | nindent 4 }}
