---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echoapp-stg
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:staging-*
spec:
  releaseName: echoapp-stg
  chart:
    git: git@github.com:edenavital5/echo_app_helm_chart.git
    path: charts/echo
    ref: staging
  values:
    image:
      repository: edenavital/echo-app
      tag: staging-48df9e0c1f3fdcd61ca0e4897cf59e8eb05819cb
    replicaCount: 1
    hpa:
      enabled: true
      maxReplicas: 10
      cpu: 50
      memory: 256Mi
