---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echoapp-stg
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:staging-*
spec:
  releaseName: echoapp-stg
  chart:
    git: git@github.com:edenavital5/echo_app_helm_chart.git
    path: charts/echo
    ref: stg
  values:
    image:
      repository: edenavital/echo-app
      tag: staging-b47cbc041794898c9f83e798d1518e649cec85bf      
    replicaCount: 1
    hpa:
      enabled: true
      maxReplicas: 10
      cpu: 50
      memory: 256Mi
