apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "echo.fullname" . }}
  labels:
    {{- include "echo.labels" . | nindent 4 }}
  annotations:
    nginx.org/proxy-connect-timeout: "120s"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ .Values.ingress.hosts.host }}
    http:
      paths:
      - backend:
          serviceName: echo-app
          servicePort: 80


